#!/bin/sh

if [[ ! -e '/sys/bus/testbus' ]]
then
	echo 'Module doesn''t seem to be loaded anyways'
	exit 1
fi

if [[ -e '/sys/bus/testbus/drivers/dcsc_driver/createnewdevice' ]]
then
	echo 'Removing module with dynamic device creation'
	# Module was loaded with dynamic device creation
	rmmod dcsc || exit 1
else
	echo 'Removing module without dynamic device creation'
	# Module was loaded with "static" device creation and one
	# default device
	rmmod dcsc || exit 1
fi





