#!/bin/bash

if [[ $# -ne  1 ]]
then
	echo "Usage: dcsc_load (interactive|fixed)"
	exit 1
fi
if [[ ($1 != "interactive") && ($1 != "fixed") ]]
then
	echo "dcsc_load: Unrecognized parameter \"$1\""
	echo "Usage: dcsc_load (interactive|fixed)"
	exit 1
fi



if [[ $1 == "interactive" ]]
then
	# Load module and allow for interactive device creation
	insmod ./dcsc.ko interactive_creation_allowed=1 || exit 1

	exit 0
fi

if [[ $1 == "fixed" ]]
then
	# Load module with only one default device
	insmod ./dcsc.ko interactive_creation_allowed=0 || exit 1

	exit 0
fi
